<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>WOMENACE.Code</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(GameAssembliesDir)/UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
