namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (alva/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile AlvaDefault = new()
    {
        LodMesh = "alva_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0311_Hair_L02>bone0313_Hair_L04A",
                "bone0316_Hair_R02>bone0318_Hair_R04A"
            ),
            SpringPresets.LongHair(
                "PonyTail1>PonyTail25"
            ),
            SpringPresets.StiffCloth(
                "bone0320_Bangs_MB01>bone0322_Bangs_MB03A",
                "bone0325_Bangs_LB02>bone0326_Bangs_LB03A",
                "bone0329_Bangs_RB02>bone0330_Bangs_RB03A"
            ),
            SpringPresets.Skirt(
                "Cape_0_0>Cape_5_0",
                "Cape_0_1>Cape_5_1",
                "Cape_0_2>Cape_5_2",
                "Cape_0_3>Cape_5_3",
                "Cape_0_4>Cape_5_4",
                "FCapeL1>FCapeL11",
                "FCapeR1>FCapeR11"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
