namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (alva/antje). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile AlvaAntje = new()
    {
        LodMesh = "alva_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0298_Hair_L01>bone0301_Hair_L04A",
                "bone0303_Hair_R01>bone0306_Hair_R04a",
                "bone0327_HairBA_M0>bone0327_HairBA_M0A"
            ),
            SpringPresets.LongHair(
                "bone0321_HairB_M0>bone0325_HairB_M4A"
            ),
            SpringPresets.StiffCloth(
                "bone0308_Bangs_MB01>bone0309_Bangs_MB02A",
                "bone0315_Bangs_RB01>bone0316_Bangs_RB02A",
                "bone0318_Bangs_MF01>bone0319_Bangs_MF02A",
                "bone0372_Tape_L01>bone0373_Tape_L02"
            ),
            SpringPresets.Ribbon(
                "bone0311_Bangs_LB01>bone0313_Bangs_LB03A"
            ),
            SpringPresets.Skirt(
                "Coat_0_0>Coat_1_0",
                "Coat_0_1>Coat_5_1",
                "Coat_0_2>Coat_5_2",
                "Coat_0_3>Coat_5_3",
                "Coat_0_4>Coat_5_4",
                "Coat_0_5>Coat_5_5",
                "Coat_0_6>Coat_5_6",
                "Coat_0_7>Coat_5_7",
                "Coat_0_8>Coat_5_8",
                "Coat_0_9>Coat_5_9",
                "Coat_0_10>Coat_5_10",
                "Coat_0_11>Coat_5_11",
                "Coat_0_12>Coat_5_12",
                "Coat_0_13>Coat_5_13",
                "Coat_0_14>Coat_5_14",
                "Coat_0_15>Coat_5_15",
                "Coat_0_16>Coat_5_16",
                "Coat_0_17>Coat_5_17"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
