namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (alva/wisteria_tidings). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile AlvaWisteriaTidings = new()
    {
        LodMesh = "alva_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0311_Hair_L02>bone0313_Hair_L04A",
                "bone0316_Hair_R02>bone0318_Hair_R04A"
            ),
            SpringPresets.LongHair(
                "PonyTail1>PonyTail25"
            ),
            SpringPresets.StiffCloth(
                "Bow_L05>Bow_L08",
                "Bow_R05>Bow_R08",
                "Cloth_L03>Cloth_L04",
                "Cloth_LB01>Cloth_LB02",
                "Cloth_LB03>Cloth_LB04",
                "Cloth_LF03>Cloth_LF04",
                "Cloth_MB01>Cloth_MB02",
                "Cloth_MB03>Cloth_MB04",
                "Cloth_R03>Cloth_R04",
                "Cloth_RB01>Cloth_RB02",
                "Cloth_RB03>Cloth_RB04",
                "Cloth_RF03>Cloth_RF04",
                "Tape_LF05>Tape_LF07",
                "Tape_RF05>Tape_RF07",
                "bone0320_Bangs_MB01>bone0322_Bangs_MB03A",
                "bone0325_Bangs_LB02>bone0326_Bangs_LB03A",
                "bone0329_Bangs_RB02>bone0330_Bangs_RB03A"
            ),
            SpringPresets.Ribbon(
                "Bow_L01>Bow_L04",
                "Bow_R01>Bow_R04",
                "Tape_LF01>Tape_LF04",
                "Tape_RF01>Tape_RF04"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_7_0",
                "Skirt_0_1>Skirt_7_1",
                "Skirt_0_2>Skirt_7_2",
                "Skirt_0_3>Skirt_7_3",
                "Skirt_0_4>Skirt_7_4",
                "Skirt_0_5>Skirt_7_5",
                "Skirt_0_6>Skirt_7_6",
                "Skirt_0_7>Skirt_7_7",
                "Skirt_0_8>Skirt_7_8",
                "Skirt_0_9>Skirt_7_9",
                "Skirt_0_10>Skirt_7_10",
                "Skirt_0_11>Skirt_7_11",
                "Skirt_0_12>Skirt_7_12",
                "Skirt_0_13>Skirt_7_13",
                "Skirt_0_14>Skirt_7_14",
                "Skirt_0_15>Skirt_7_15",
                "Skirt_0_16>Skirt_7_16",
                "Skirt_0_17>Skirt_7_17",
                "Skirt_0_18>Skirt_7_18",
                "Skirt_0_19>Skirt_7_19",
                "Skirt_0_20>Skirt_7_20"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
