namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (asteria/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile AsteriaDefault = new()
    {
        LodMesh = "asteria_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "Hair_L01>Hair_L04",
                "Hair_L06>Hair_L09",
                "Hair_LB01>Hair_LB04",
                "Hair_MB01>Hair_MB05",
                "Hair_MB06>Hair_MB09",
                "Hair_R01>Hair_R04",
                "Hair_R06>Hair_R09",
                "Hair_RB01>Hair_RB04"
            ),
            SpringPresets.StiffCloth(
                "Bangs_LF01>Bangs_LF03",
                "Bangs_MF01>Bangs_MF03",
                "Bangs_MF06>Bangs_MF07",
                "Bangs_MF010>Bangs_MF012",
                "Bangs_RF01>Bangs_RF03",
                "Cloth_L070>Cloth_L071",
                "Cloth_L072>Cloth_L073",
                "Cloth_MF075>Cloth_MF077",
                "Cloth_R070>Cloth_R071",
                "Cloth_R072>Cloth_R073"
            ),
            SpringPresets.Ribbon(
                "Cloth_L050>Cloth_L053"
            ),
            SpringPresets.Skirt(
                "Jacket_0_3>Jacket_6_3",
                "Jacket_0_4>Jacket_6_4",
                "Jacket_0_5>Jacket_6_5",
                "Jacket_0_6>Jacket_6_6",
                "Jacket_0_7>Jacket_6_7",
                "Jacket_0_8>Jacket_6_8",
                "Jacket_0_9>Jacket_6_9",
                "Jacket_0_10>Jacket_6_10",
                "Jacket_0_11>Jacket_6_11",
                "Jacket_0_12>Jacket_6_12",
                "Jacket_0_13>Jacket_6_13",
                "Jacket_0_14>Jacket_6_14",
                "Jacket_0_15>Jacket_6_15",
                "Jacket_0_16>Jacket_6_16",
                "Jacket_0_17>Jacket_6_17"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_7_0",
                "Skirt_0_1>Skirt_7_1",
                "Skirt_0_2>Skirt_7_2",
                "Skirt_0_3>Skirt_7_3",
                "Skirt_0_4>Skirt_7_4",
                "Skirt_0_5>Skirt_7_5",
                "Skirt_0_6>Skirt_7_6",
                "Skirt_0_7>Skirt_7_7",
                "Skirt_0_8>Skirt_7_8",
                "Skirt_0_9>Skirt_7_9",
                "Skirt_0_10>Skirt_7_10",
                "Skirt_0_11>Skirt_7_11",
                "Skirt_0_12>Skirt_7_12",
                "Skirt_0_13>Skirt_7_13",
                "Skirt_0_14>Skirt_7_14",
                "Skirt_0_15>Skirt_7_15",
                "Skirt_0_16>Skirt_7_16",
                "Skirt_0_17>Skirt_7_17",
                "Skirt_0_18>Skirt_7_18",
                "Skirt_0_19>Skirt_7_19",
                "Skirt_0_20>Skirt_7_20"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
