namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (cheyanne/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile CheyanneDefault = new()
    {
        LodMesh = "cheyanne_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB1>HairB3",
                "HairC2>HairC5",
                "HairD2>HairD5",
                "HairE1>HairE3",
                "HairF1>HairF3",
                "HairG1>HairG3"
            ),
            SpringPresets.StiffCloth(
                "Hat01>Hat03",
                "card01>card02"
            ),
            SpringPresets.Skirt(
                "Jacket_0_2>Jacket_9_2",
                "Jacket_0_3>Jacket_9_3",
                "Jacket_0_4>Jacket_9_4",
                "Jacket_0_5>Jacket_9_5",
                "Jacket_0_6>Jacket_9_6",
                "Jacket_0_7>Jacket_9_7",
                "Jacket_0_8>Jacket_9_8",
                "Jacket_0_9>Jacket_9_9",
                "Jacket_0_10>Jacket_9_10",
                "Jacket_0_11>Jacket_9_11",
                "Jacket_0_12>Jacket_9_12",
                "Jacket_0_13>Jacket_9_13",
                "Jacket_0_14>Jacket_9_14",
                "Jacket_0_15>Jacket_9_15",
                "Jacket_0_16>Jacket_9_16",
                "Jacket_0_17>Jacket_9_17",
                "Jacket_0_18>Jacket_9_18",
                "Jacket_0_19>Jacket_9_19"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15",
                "Skirt_0_16>Skirt_6_16",
                "Skirt_0_17>Skirt_6_17"
            ),
        },
        Colliders = HumanoidColliders(1.350f),
    };
}
