namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (cheyanne/maiden_debut). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile CheyanneMaidenDebut = new()
    {
        LodMesh = "cheyanne_maiden_debut_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "Hair04>Hair06",
                "HairBow03>HairBow04",
                "Hair_L04>Hair_L06",
                "Hair_LB08>Hair_LB012",
                "Hair_LF13>Hair_LF14_End",
                "Hair_MF2>Hair_MF3_End",
                "Hair_R04>Hair_R06",
                "Hair_RF13>Hair_RF14_End"
            ),
            SpringPresets.LongHair(
                "Hair_LB01>Hair_LB07"
            ),
            SpringPresets.StiffCloth(
                "Cord_L07>Cord_L08",
                "Cord_L09>Cord_L10",
                "Headwear_LB015>Headwear_LB016",
                "Headwear_LB017>Headwear_LB019",
                "Headwear_LB020>Headwear_LB023",
                "Headwear_LB024>Headwear_LB026"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15",
                "Skirt_0_16>Skirt_6_16",
                "Skirt_0_17>Skirt_6_17"
            ),
        },
        Colliders = HumanoidColliders(1.350f),
    };
}
