namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (helen/starlit_waltz). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile HelenStarlitWaltz = new()
    {
        LodMesh = "helen_waltz_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA7",
                "HairB1>HairB7",
                "HairC1>HairC9"
            ),
            SpringPresets.LongHair(
                "HairD1>HairD9",
                "HairE1>HairE11"
            ),
            SpringPresets.StiffCloth(
                "Chest_L>Cloth_R02",
                "Chest_R>Cloth_L02",
                "Cloth_MF01>Cloth_MF03"
            ),
            SpringPresets.Ribbon(
                "Pifeng_L01>Pifeng_L06",
                "Pifeng_L07>Pifeng_L011",
                "Pifeng_L012>Pifeng_L017",
                "Pifeng_L018>Pifeng_L023",
                "Pifeng_R01>Pifeng_R06",
                "Pifeng_R07>Pifeng_R011",
                "Pifeng_R012>Pifeng_R017",
                "Pifeng_R018>Pifeng_R023"
            ),
            SpringPresets.Gown(
                "Skirt_0_0>Skirt_9_0",
                "Skirt_0_1>Skirt_9_1",
                "Skirt_0_2>Skirt_9_2",
                "Skirt_0_3>Skirt_3_3",
                "Skirt_0_4>Skirt_9_4",
                "Skirt_0_5>Skirt_9_5",
                "Skirt_0_6>Skirt_9_6",
                "Skirt_0_7>Skirt_9_7",
                "Skirt_0_8>Skirt_9_8",
                "Skirt_0_10>Skirt_9_10",
                "Skirt_0_11>Skirt_9_11",
                "Skirt_0_12>Skirt_9_12",
                "Skirt_0_13>Skirt_9_13",
                "Skirt_0_14>Skirt_9_14",
                "Skirt_0_15>Skirt_9_15",
                "Skirt_0_16>Skirt_9_16",
                "Skirt_0_17>Skirt_9_17",
                "Skirt_1_9>Skirt_9_9"
            ),
        },
        Colliders = HumanoidColliders(1.679f),
    };
}
