namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (helen/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile HelenDefault = new()
    {
        LodMesh = "helen_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA7",
                "HairB1>HairB7",
                "HairBandA1>HairBandA3",
                "HairBandB1>HairBandB3",
                "HairC1>HairC9",
                "HairD1>HairD9"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE9"
            ),
            SpringPresets.StiffCloth(
                "Cloth_L02>Cloth_L012",
                "Cloth_L05>Cloth_L011",
                "Cloth_L13>Cloth_L19"
            ),
            SpringPresets.Ribbon(
                "Cloth_L03>Cloth_L010",
                "Tape_MF01>Tape_MF06"
            ),
            SpringPresets.DrapedRibbon("Spine2",
                "Cloth_L06>Cloth_L20",
                "Cloth_L15>Cloth_L18",
                "Cloth_LF01>Cloth_LF015",
                "Cloth_RF01>Cloth_RF015"
            ),
        },
        Colliders = HumanoidColliders(1.679f),
    };
}
