namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (jiangyu/raindrop). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile JiangyuRaindrop = new()
    {
        LodMesh = "jiangyu_raindrop_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA2",
                "HairB1>HairB2",
                "HairC3>HairC7",
                "HairD3>HairD7",
                "HairE3>HairE7",
                "HairF3>HairF7",
                "HairG1>HairG4",
                "HairH1>HairH4",
                "HairI1>HairI4",
                "HairJ1>HairJ3",
                "HairK1>HairK3",
                "HairL1>HairL3"
            ),
            SpringPresets.LongHair(
                "HairM1>HairM21",
                "HairN1>HairN21"
            ),
            SpringPresets.StiffCloth(
                "P1-BeltA1>P1-BeltA3",
                "P1-BeltB1>P1-BeltB3",
                "P1-BeltC1>P1-BeltC2",
                "P1-BeltD1>P1-BeltD2",
                "P1-BeltE1>P1-BeltE2"
            ),
            SpringPresets.Ribbon(
                "P1-HatA1>P1-HatA3",
                "P1-HatB1>P1-HatB3",
                "SleeveA1.L>SleeveA4.L",
                "SleeveA1.R>SleeveA4.R",
                "SleeveB1.L>SleeveB4.L",
                "SleeveB1.R>SleeveB4.R",
                "SleeveC1.L>SleeveC4.L",
                "SleeveC1.R>SleeveC4.R",
                "SleeveD1.L>SleeveD4.L",
                "SleeveD1.R>SleeveD4.R"
            ),
            SpringPresets.Skirt(
                "BeltA1>BeltA4",
                "BeltB1>BeltB4"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
