namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (jiangyu/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile JiangyuDefault = new()
    {
        LodMesh = "jiangyu_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairC1>HairC7",
                "HairD1>HairD7",
                "HairE1>HairE5",
                "HairF1>HairF7",
                "HairG1>HairG5",
                "HairH1>HairH5"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA7",
                "HairB1>HairB7",
                "HairI1>HairI21",
                "HairJ1>HairJ21"
            ),
            SpringPresets.StiffCloth(
                "HatC1>HatC5",
                "HatD1>HatD5",
                "Lf_piaodai_Jnt4>Lf_piaodai_Jnt4_End",
                "Rt_armor_Jnt1>Rt_armor_Jnt1_End",
                "Rt_piaodai_Jnt4>Rt_piaodai_Jnt4_End"
            ),
            SpringPresets.Ribbon(
                "HatA1>HatA-A2",
                "HatB1>HatB5",
                "HatE1>HatE5",
                "HatF1>HatF5"
            ),
            SpringPresets.DrapedRibbon("Spine2",
                "Lf_cloth_Jnt1>Lf_cloth_Jnt5",
                "Lf_cloth_Jnt-B1>Lf_cloth_Jnt-B3",
                "Rt_cloth_Jnt1>Rt_cloth_Jnt5",
                "Rt_cloth_Jnt-B1>Rt_cloth_Jnt-B3"
            ),
            SpringPresets.Accessory(
                "Lf_bag_Jnt1>Lf_bag_Jnt1_End",
                "Rt_bag_Jnt1>Rt_bag_Jnt1_End"
            ),
            SpringPresets.Skirt(
                "BeltA1>BeltA9",
                "BeltB1>BeltB7"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15"
            ),
        },
        Colliders = HumanoidColliders(1.552f),
    };
}
