namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (klukai/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile KlukaiDefault = new()
    {
        LodMesh = "klukai_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairD1>HairD5",
                "HairE1>HairE5",
                "HairF1>HairF3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA17",
                "HairB1>HairB17",
                "HairC1>HairC21",
                "HairC2-A1>HairC2-A20",
                "HairC2-B1>HairC2-B20"
            ),
            SpringPresets.StiffCloth(
                "bone0316_stick4>bone0317_stick5a",
                "bone0382_Pendant1>bone0383_Pendant2a"
            ),
            SpringPresets.Ribbon(
                "bone0374_Bigbag>bone0376_cord_L1a",
                "bone0378_cord_R>bone0379_cord_R1a"
            ),
        },
        Colliders = HumanoidColliders(1.471f),
    };
}
