namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (klukai/speedstar). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile KlukaiSpeedstar = new()
    {
        LodMesh = "klukai_speedstar_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairD1>HairD5",
                "HairE1>HairE5",
                "HairF1>HairF3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA17",
                "HairB1>HairB17",
                "HairC1-A1>HairC1-A20",
                "HairC1-B1>HairC1-B20",
                "HairC1>HairC21"
            ),
        },
        Colliders = HumanoidColliders(1.471f),
    };
}
