namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (klukai/indigo_oath). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile KlukaiIndigoOath = new()
    {
        LodMesh = "klukai_indigo_oath_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairH1>HairH2",
                "HairI1>HairI2",
                "HairJ1>HairJ3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA9",
                "HairB1>HairB9",
                "HairC1>HairC21",
                "HairD1>HairD21",
                "HairE1>HairE21",
                "HairF1>HairF21",
                "HairG1>HairG9"
            ),
            SpringPresets.StiffCloth(
                "BowA2>BowA3",
                "BowA4>BowA5",
                "BowB2>BowB3",
                "BowB4>BowB5",
                "Chest_L>Flower_LF01",
                "Cloth_LB01>Cloth_LB05",
                "Cloth_LB02>Cloth_LB06",
                "Cloth_MF01>Cloth_MF02",
                "Cloth_RB01>Cloth_RB05",
                "Cloth_RB02>Cloth_RB06"
            ),
            SpringPresets.Ribbon(
                "VeilA1>VeilA4",
                "VeilB2>VeilB4",
                "VeilC1>VeilC4"
            ),
            SpringPresets.Skirt(
                "BowA6>BowA12",
                "BowA13>BowA19",
                "BowA20>BowA26",
                "BowA27>BowA33",
                "BowB6>BowB10",
                "BowB11>BowB13"
            ),
            SpringPresets.Gown(
                "Skirt_0_0>Skirt_2_0",
                "Skirt_0_1>Skirt_2_1",
                "Skirt_0_2>Skirt_11_2",
                "Skirt_0_3>Skirt_11_3",
                "Skirt_0_4>Skirt_11_4",
                "Skirt_0_5>Skirt_11_5",
                "Skirt_0_6>Skirt_11_6",
                "Skirt_0_7>Skirt_11_7",
                "Skirt_0_8>Skirt_11_8",
                "Skirt_0_9>Skirt_11_9",
                "Skirt_0_10>Skirt_11_10",
                "Skirt_0_11>Skirt_11_11",
                "Skirt_0_12>Skirt_11_12",
                "Skirt_0_13>Skirt_11_13",
                "Skirt_0_14>Skirt_11_14",
                "Skirt_0_15>Skirt_11_15",
                "Skirt_0_16>Skirt_11_16",
                "Skirt_0_17>Skirt_11_17",
                "Skirt_0_18>Skirt_11_18",
                "Skirt_0_19>Skirt_11_19",
                "Skirt_0_20>Skirt_11_20",
                "Skirt_0_21>Skirt_11_21",
                "Skirt_0_22>Skirt_11_22",
                "Skirt_0_23>Skirt_11_23",
                "Skirt_0_24>Skirt_2_24"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
