namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (koleda/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile KoledaDefault = new()
    {
        LodMesh = "koleda_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairI1>HairI4",
                "HairJ1>HairJ4",
                "HairK1>HairK3",
                "HairL1>HairL3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21",
                "HairB1>HairB21",
                "HairC1>HairC21",
                "HairD1>HairD21",
                "HairE1>HairE21",
                "HairF1>HairF21",
                "HairG1>HairG17",
                "HairH1>HairH17"
            ),
            SpringPresets.Ribbon(
                "SleeveA2.L>SleeveA4.L",
                "SleeveA2.R>SleeveA4.R",
                "SleeveB2.L>SleeveB4.L",
                "SleeveB2.R>SleeveB4.R",
                "SleeveC2.L>SleeveC4.L",
                "SleeveC2.R>SleeveC4.R"
            ),
            SpringPresets.Skirt(
                "CapeA1.L>CapeA9.L",
                "CapeA1.R>CapeA9.R",
                "CapeB1.L>CapeB9.L",
                "CapeB1.R>CapeB9.R",
                "CapeC1.L>CapeC9.L",
                "CapeC1.R>CapeC9.R",
                "CapeD1.L>CapeD9.L",
                "CapeD1.R>CapeD9.R"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
