namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (koleda/spooms). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile KoledaSpooms = new()
    {
        LodMesh = "koleda_spooms_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairG1>HairG7",
                "HairH1>HairH7"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21",
                "HairB1>HairB21",
                "HairC1>HairC21",
                "HairD1>HairD21",
                "HairE1>HairE21",
                "HairF1>HairF21",
                "HairI1>HairI17",
                "HairJ1>HairJ17"
            ),
            SpringPresets.StiffCloth(
                "Bow_L01>Bow_L03",
                "Bow_L04>Bow_L06",
                "Bow_R01>Bow_R03",
                "Bow_R04>Bow_R06"
            ),
            SpringPresets.Ribbon(
                "Cloth_L01>Cloth_L03",
                "Cloth_LF02>Cloth_LF04",
                "Cloth_MB02>Cloth_MB04",
                "Cloth_R01>Cloth_R03",
                "Cloth_RF02>Cloth_RF04"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
