namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (lenna/vitality_magic). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LennaVitalityMagic = new()
    {
        LodMesh = "lenna_vitality_magic_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB1>HairB5",
                "HairC1>HairC5",
                "HairD1>HairD7"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE25",
                "HairF1>HairF25",
                "HairG1>HairG9",
                "HairH1>HairH9"
            ),
            SpringPresets.StiffCloth(
                "BigbowA1>BigbowA5",
                "BigbowC1>BigbowC5",
                "BigbowD1>BigbowD5",
                "BigbowE1>BigbowE5",
                "Bow_Hip3>Bow_Hip4",
                "Bow_Hip>Bow_Hip2",
                "Bow_ShoesL2>Bow_ShoesL3",
                "Bow_ShoesL>Bow_ShoesL1",
                "Bow_ShoesR2>Bow_ShoesR3",
                "Bow_ShoesR>Bow_ShoesR1",
                "Bow_hand_L2>Bow_hand_L3",
                "Bow_hand_L>Bow_hand_L1",
                "Bow_hand_R2>Bow_hand_R3",
                "Bow_hand_R>Bow_hand_R1",
                "HatA1>HatA5",
                "HatB1>HatB5",
                "HatC1>HatC5",
                "HatD1>HatD5",
                "HatE1>HatE3",
                "Tie_L>Tie_L2",
                "Tie_R>Tie_R2",
                "Tie_neck_L>Tie_neck_L1",
                "Tie_neck_R>Tie_neck_R1",
                "bow_chest_L>bow_chest_L2",
                "bow_chest_R>bow_chest_R2"
            ),
            SpringPresets.Ribbon(
                "BigbowB1>BigbowB5"
            ),
            SpringPresets.Accessory(
                "Bow_weapon2>Bow_weapon3",
                "Bow_weapon>Bow_weapon1"
            ),
            SpringPresets.Skirt(
                "BigbowF1>BigbowF7"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_5_0",
                "Skirt_0_1>Skirt_5_1",
                "Skirt_0_2>Skirt_5_2",
                "Skirt_0_3>Skirt_5_3",
                "Skirt_0_4>Skirt_5_4",
                "Skirt_0_5>Skirt_5_5",
                "Skirt_0_6>Skirt_5_6",
                "Skirt_0_7>Skirt_5_7",
                "Skirt_0_8>Skirt_5_8",
                "Skirt_0_9>Skirt_5_9",
                "Skirt_0_10>Skirt_5_10",
                "Skirt_0_11>Skirt_5_11",
                "Skirt_0_12>Skirt_5_12",
                "Skirt_0_13>Skirt_5_13",
                "Skirt_0_14>Skirt_5_14",
                "Skirt_0_15>Skirt_5_15"
            ),
        },
        Colliders = HumanoidColliders(1.472f),
    };
}
