namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (lenna/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LennaDefault = new()
    {
        LodMesh = "lenna_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB1>HairB5",
                "HairC1>HairC5",
                "HairD1>HairD7"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE25",
                "HairF1>HairF25",
                "HairG1>HairG9",
                "HairH1>HairH9"
            ),
            SpringPresets.StiffCloth(
                "RibbonLA1>RibbonLA2",
                "RibbonRA1>RibbonRA2",
                "collar_L_Jnt1>collar_L_Jnt1_End",
                "collar_L_Jnt>collar_L_Jnt_End",
                "collar_M_Jnt>collar_M_Jnt_End",
                "collar_R_Jnt1>collar_R_Jnt1_End",
                "collar_R_Jnt>collar_R_Jnt_End"
            ),
            SpringPresets.Ribbon(
                "RibbonLB1>RibbonLB5",
                "RibbonRB1>RibbonRB5"
            ),
            SpringPresets.Skirt(
                "Jacket_0_3>Jacket_5_3",
                "Jacket_0_4>Jacket_5_4",
                "Jacket_0_5>Jacket_5_5",
                "Jacket_0_6>Jacket_5_6",
                "Jacket_0_7>Jacket_5_7",
                "Jacket_0_8>Jacket_5_8",
                "Jacket_0_9>Jacket_5_9",
                "Jacket_0_10>Jacket_5_10",
                "Jacket_0_11>Jacket_5_11",
                "Jacket_0_12>Jacket_5_12",
                "Jacket_0_13>Jacket_5_13"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_5_0",
                "Skirt_0_1>Skirt_5_1",
                "Skirt_0_2>Skirt_5_2",
                "Skirt_0_3>Skirt_5_3",
                "Skirt_0_4>Skirt_5_4",
                "Skirt_0_5>Skirt_5_5",
                "Skirt_0_6>Skirt_5_6",
                "Skirt_0_7>Skirt_5_7",
                "Skirt_0_8>Skirt_5_8",
                "Skirt_0_9>Skirt_5_9",
                "Skirt_0_10>Skirt_5_10",
                "Skirt_0_11>Skirt_5_11",
                "Skirt_0_12>Skirt_5_12",
                "Skirt_0_13>Skirt_5_13",
                "Skirt_0_14>Skirt_5_14",
                "Skirt_0_15>Skirt_5_15"
            ),
        },
        Colliders = HumanoidColliders(1.471f),
    };
}
