namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (lenna/flying_phantom). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LennaFlyingPhantom = new()
    {
        LodMesh = "lenna_flying_phantom_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB1>HairB5",
                "HairC1>HairC5",
                "HairD1>HairD7"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE25",
                "HairF1>HairF25",
                "HairG1>HairG9",
                "HairH1>HairH9"
            ),
            SpringPresets.Ribbon(
                "bone0396_cloth_M_skin>bone0397_cloth_M_skin2"
            ),
            SpringPresets.Skirt(
                "CapeA2.L>CapeA7.L",
                "CapeA2.R>CapeA7.R",
                "CapeB2.L>CapeB8.L",
                "CapeB2.R>CapeB8.R"
            ),
        },
        Colliders = HumanoidColliders(1.479f),
    };
}
