namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (leva/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LevaDefault = new()
    {
        LodMesh = "leva_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0247_Hair_LF02>bone0249_Hair_LF04",
                "bone0260_Hair_RF02>bone0262_Hair_RF04",
                "bone0264_Hair_RF06>bone0265_Hair_RF07"
            ),
            SpringPresets.LongHair(
                "BackHairA1>BackHairA17",
                "BackHairB1>BackHairB17",
                "BackHairC1>BackHairC17",
                "bone0285_Hair_L03>bone0288_Hair_L06"
            ),
            SpringPresets.Ribbon(
                "bone0383_Cltoh_MF01>bone0386_Cltoh_MF04",
                "bone0407_Cltoh_LF10>bone0409_Cltoh_LF12",
                "bone0415_Cltoh_RF11>bone0417_Cltoh_RF13"
            ),
            SpringPresets.Skirt(
                "Coat_0_1>Coat_7_1",
                "Coat_0_2>Coat_7_2",
                "Coat_0_3>Coat_7_3",
                "Coat_0_4>Coat_7_4",
                "Coat_0_5>Coat_7_5",
                "Coat_0_6>Coat_7_6",
                "Coat_0_7>Coat_7_7",
                "Coat_0_8>Coat_7_8",
                "Coat_0_9>Coat_7_9",
                "Coat_0_10>Coat_7_10",
                "Coat_0_11>Coat_7_11",
                "Coat_0_12>Coat_7_12",
                "Coat_0_13>Coat_7_13",
                "Coat_0_14>Coat_7_14",
                "Coat_0_15>Coat_7_15",
                "Coat_0_16>Coat_7_16",
                "Coat_0_17>Coat_7_17",
                "Coat_0_18>Coat_7_18",
                "Coat_0_19>Coat_7_19"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15",
                "Skirt_0_16>Skirt_6_16",
                "Skirt_0_17>Skirt_6_17"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
