namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (leva/diamond_flower). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LevaDiamondFlower = new()
    {
        LodMesh = "leva_diamond_flower_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0248_Hair_LF03>bone0249_Hair_LF04",
                "bone0260_Hair_RF02>bone0262_Hair_RF04",
                "bone0264_Hair_RF06>bone0265_Hair_RF07"
            ),
            SpringPresets.LongHair(
                "BackHairA1>BackHairA17",
                "BackHairB1>BackHairB17",
                "BackHairC1>BackHairC17",
                "bone0285_Hair_L03>bone0288_Hair_L06"
            ),
            SpringPresets.StiffCloth(
                "bone0290_HeadBow_A>bone0291_HeadBow_A1",
                "bone0293_HeadBow_B>bone0294_HeadBow_B1",
                "bone0379_Scarf_B>bone0380_Scarf_B1"
            ),
            SpringPresets.Ribbon(
                "bone0374_Scarf_F>bone0377_Scarf_F3"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_7_0",
                "Skirt_0_1>Skirt_7_1",
                "Skirt_0_2>Skirt_7_2",
                "Skirt_0_3>Skirt_7_3",
                "Skirt_0_4>Skirt_7_4",
                "Skirt_0_5>Skirt_7_5",
                "Skirt_0_6>Skirt_7_6",
                "Skirt_0_7>Skirt_7_7",
                "Skirt_0_8>Skirt_7_8",
                "Skirt_0_9>Skirt_7_9",
                "Skirt_0_10>Skirt_7_10",
                "Skirt_0_11>Skirt_7_11",
                "Skirt_0_12>Skirt_7_12",
                "Skirt_0_13>Skirt_7_13",
                "Skirt_0_14>Skirt_7_14",
                "Skirt_0_15>Skirt_7_15",
                "Skirt_0_16>Skirt_7_16",
                "Skirt_0_17>Skirt_7_17",
                "Skirt_0_18>Skirt_7_18",
                "Skirt_0_19>Skirt_7_19",
                "Skirt_0_20>Skirt_7_20"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
