namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (leva/sultry_tempo). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LevaSultryTempo = new()
    {
        LodMesh = "leva_sultry_tempo_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0247_Hair_LF02>bone0249_Hair_LF04",
                "bone0260_Hair_RF02>bone0262_Hair_RF04",
                "bone0264_Hair_RF06>bone0265_Hair_RF07"
            ),
            SpringPresets.LongHair(
                "BackHairA1>BackHairA17",
                "BackHairB1>BackHairB17",
                "BackHairC1>BackHairC17",
                "bone0285_Hair_L03>bone0288_Hair_L06"
            ),
            SpringPresets.StiffCloth(
                "Cloth_L02>Cloth_L03_End",
                "Cloth_L04>Cloth_L04_End",
                "Cloth_R02>Cloth_R03_End",
                "Cloth_R04>Cloth_R04_End"
            ),
            SpringPresets.Ribbon(
                "WorkCard_M01>WorkCard_M04_End"
            ),
        },
        Colliders = HumanoidColliders(1.479f),
    };
}
