namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (lewis/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile LewisDefault = new()
    {
        LodMesh = "lewis_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA2>HairA4",
                "HairB1>HairB3",
                "HairC1>HairC3",
                "HairD2>HairD9"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE17",
                "HairF1>HairF17",
                "HairG1>HairG17",
                "HairH1>HairH17",
                "HairI1>HairI17",
                "HairJ1>HairJ17",
                "HairK1>HairK9"
            ),
            SpringPresets.StiffCloth(
                "Cloth_B03>Cloth_B08",
                "Cloth_B04>Cloth_B09",
                "Cloth_B05>Cloth_B010",
                "Cloth_B06>Cloth_B07",
                "Cloth_F02>Cloth_F06",
                "Cloth_F03>Cloth_F07",
                "Cloth_L03>Cloth_L09",
                "Cloth_L05>Cloth_L010",
                "Cloth_L07>Cloth_L011",
                "Cloth_R03>Cloth_R011",
                "Cloth_R05>Cloth_R010",
                "Cloth_R07>Cloth_R09"
            ),
            SpringPresets.Accessory(
                "Bag_R12>Bag_R06"
            ),
            SpringPresets.Skirt(
                "OutSkirt_0_1>OutSkirt_10_1",
                "OutSkirt_0_2>OutSkirt_10_2",
                "OutSkirt_0_3>OutSkirt_10_3",
                "OutSkirt_0_4>OutSkirt_10_4",
                "OutSkirt_0_5>OutSkirt_10_5",
                "OutSkirt_0_6>OutSkirt_10_6",
                "OutSkirt_0_7>OutSkirt_10_7",
                "OutSkirt_0_8>OutSkirt_10_8",
                "OutSkirt_0_9>OutSkirt_10_9",
                "OutSkirt_0_10>OutSkirt_10_10",
                "OutSkirt_0_11>OutSkirt_10_11",
                "OutSkirt_0_12>OutSkirt_10_12",
                "OutSkirt_0_13>OutSkirt_10_13",
                "OutSkirt_0_14>OutSkirt_10_14",
                "OutSkirt_0_15>OutSkirt_10_15",
                "OutSkirt_0_16>OutSkirt_10_16",
                "OutSkirt_0_17>OutSkirt_10_17",
                "OutSkirt_0_18>OutSkirt_10_18",
                "OutSkirt_0_19>OutSkirt_10_19",
                "OutSkirt_0_20>OutSkirt_10_20",
                "OutSkirt_0_21>OutSkirt_10_21"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
