namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (makiatto/steamy_vacance). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile MakiattoSteamyVacance = new()
    {
        LodMesh = "makiatto_steamy_vacance_LOD0",
        Chains = new[]
        {
            SpringPresets.StiffCloth(
                "bangsB_L_Bnd1>bangsB_L_Bnd3",
                "bangsB_R_Bnd1>bangsB_R_Bnd3",
                "bangs_L_Bnd1>bangs_L_Bnd2",
                "bangs_M_Bnd1>bangs_M_Bnd2"
            ),
            SpringPresets.Ribbon(
                "Streamer5>Streamer7",
                "Streamer>Streamer4",
                "Towel_0_0>Towel_7_0",
                "Towel_0_1>Towel_7_1",
                "Towel_0_2>Towel_7_2",
                "Towel_0_3>Towel_7_3",
                "Towel_0_4>Towel_7_4",
                "Towel_0_5>Towel_7_5",
                "Towel_0_6>Towel_7_6",
                "Towel_0_7>Towel_7_7",
                "Towel_0_8>Towel_7_8",
                "Towel_0_9>Towel_7_9",
                "Towel_0_10>Towel_7_10",
                "Towel_0_11>Towel_7_11",
                "Towel_0_12>Towel_7_12",
                "Towel_0_13>Towel_7_13",
                "Towel_0_14>Towel_7_14",
                "Towel_0_15>Towel_7_15",
                "Towel_0_16>Towel_7_16",
                "Towel_0_17>Towel_7_17",
                "Towel_0_18>Towel_7_18",
                "Towel_0_19>Towel_7_19",
                "Towel_0_20>Towel_7_20"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
