namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (makiatto/ballroom). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile MakiattoBallroom = new()
    {
        LodMesh = "makiatto_ballroom_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA7",
                "HairB1>HairB5",
                "HairC1>HairC7",
                "HairE1>HairE5",
                "HairF1>HairF6"
            ),
            SpringPresets.LongHair(
                "BackHairA1>BackHairA17",
                "BackHairB1>BackHairB17",
                "BackHairC1>BackHairC17",
                "HairD1>HairD13"
            ),
            // The sleeve ribbon tied round her left forearm, hanging from it.
            SpringPresets.DrapedRibbon(null,
                "BowRibbonA1>BowRibbonA7",
                "BowRibbonB1>BowRibbonB7"
            ),
            SpringPresets.Ribbon(
                "NeckBowL1>NeckBowL17",
                "NeckBowR1>NeckBowR17"
            ),
            SpringPresets.Gown(
                "Skirt_0_0>Skirt_9_0",
                "Skirt_0_1>Skirt_9_1",
                "Skirt_0_2>Skirt_9_2",
                "Skirt_0_3>Skirt_9_3",
                "Skirt_0_4>Skirt_9_4",
                "Skirt_0_5>Skirt_9_5",
                "Skirt_0_6>Skirt_9_6",
                "Skirt_0_7>Skirt_9_7",
                "Skirt_0_8>Skirt_9_8",
                "Skirt_0_9>Skirt_9_9",
                "Skirt_0_10>Skirt_9_10",
                "Skirt_0_11>Skirt_9_11",
                "Skirt_0_12>Skirt_9_12",
                "Skirt_0_13>Skirt_9_13",
                "Skirt_0_14>Skirt_9_14",
                "Skirt_0_15>Skirt_9_15",
                "Skirt_0_16>Skirt_9_16",
                "Skirt_0_17>Skirt_9_17",
                "Skirt_0_18>Skirt_9_18",
                "Skirt_0_19>Skirt_9_19",
                "Skirt_0_20>Skirt_9_20",
                "Skirt_0_21>Skirt_9_21",
                "Skirt_0_22>Skirt_9_22",
                "Skirt_0_23>Skirt_9_23"
            ),
        },
        Colliders = HumanoidColliders(1.552f),
    };
}
