namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (makiatto/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile MakiattoDefault = new()
    {
        LodMesh = "makiatto_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairB1>HairB7",
                "HairC1>HairC5",
                "HairD1>HairD5",
                "HairE1>HairE7",
                "HairF1>HairF7",
                "HairG1>HairG5",
                "HairH3>HairH7"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21"
            ),
            SpringPresets.StiffCloth(
                "HatA1>HatA5",
                "HatB1>HatB3",
                "HatC1>HatC5",
                "HatD1>HatD3",
                "bone0776_Macqiato_piaodai_Jnt1>bone0776_Macqiato_piaodai_Jnt11",
                "bone0790_Macqiato_piaodai_Jnt3>bone0790_Macqiato_piaodai_Jnt31"
            ),
            SpringPresets.Ribbon(
                "TieA1>TieA11"
            ),
            SpringPresets.Accessory(
                "bone0753_Macqiato_weapon_Ctrl1_Jnt_skin>bone0753_Macqiato_weapon_Ctrl1_Jnt_skin1"
            ),
            SpringPresets.Skirt(
                "Jacket_0_3>Jacket_9_3",
                "Jacket_0_4>Jacket_9_4",
                "Jacket_0_5>Jacket_9_5",
                "Jacket_0_6>Jacket_9_6",
                "Jacket_0_7>Jacket_9_7",
                "Jacket_0_8>Jacket_9_8",
                "Jacket_0_9>Jacket_9_9",
                "Jacket_0_10>Jacket_9_10",
                "Jacket_0_11>Jacket_9_11",
                "Jacket_0_12>Jacket_9_12",
                "Jacket_0_13>Jacket_9_13"
            ),
        },
        Colliders = HumanoidColliders(1.552f),
    };
}
