namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (mechty/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile MechtyDefault = new()
    {
        LodMesh = "mechty_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA7",
                "HairB1>HairB5",
                "HairC1>HairC7",
                "HairD1>HairD7",
                "HairE1>HairE5",
                "HairF1>HairF3",
                "HairG1>HairG5",
                "HairH1>HairH3",
                "HairI1>HairI3",
                "HairJ1>HairJ7",
                "HairK1>HairK5"
            ),
            SpringPresets.StiffCloth(
                "bone0328_Rt_cloth_Jnt18>bone0328_Rt_cloth_Jnt18a",
                "bone0370_Lf_cloth_Jnt18>bone0370_Lf_cloth_Jnt18a",
                "bone0461_Rt_shoe_Jnt1>bone0461_Rt_shoe_Jnt1a",
                "bone0491_Lf_shoe_Jnt1>bone0491_Lf_shoe_Jnt1a",
                "bone0493_Lf_daizi_Jnt5>bone0493_Lf_daizi_Jnt5a",
                "bone0500_Lf_daizi_Jnt1>bone0500_Lf_daizi_Jnt1a"
            ),
            SpringPresets.Accessory(
                "bone0508_Mid_bag_Ctrl1_Jnt_skin>bone0510_Lf_bag_Jnt1a",
                "bone0512_Rt_bag_Jnt1>bone0513_Rt_bag_Jnt2a"
            ),
            SpringPresets.Skirt(
                "Coat_0_1>Coat_9_1",
                "Coat_0_2>Coat_9_2",
                "Coat_0_3>Coat_9_3",
                "Coat_0_4>Coat_9_4",
                "Coat_0_5>Coat_9_5",
                "Coat_0_6>Coat_9_6",
                "Coat_0_7>Coat_9_7",
                "Coat_0_8>Coat_9_8",
                "Coat_0_9>Coat_9_9",
                "Coat_0_10>Coat_9_10",
                "Coat_0_11>Coat_9_11",
                "Coat_0_12>Coat_9_12",
                "Coat_0_13>Coat_9_13",
                "Coat_0_14>Coat_9_14",
                "Coat_0_15>Coat_9_15"
            ),
        },
        Colliders = HumanoidColliders(1.350f),
    };
}
