namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (ots14/destined_love). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile Ots14DestinedLove = new()
    {
        LodMesh = "ots14_destined_love_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "Hair_LF02>Hair_LF03_End",
                "Hair_LF05>Hair_LF06_End",
                "Hair_MF02>Hair_MF03_End",
                "Hair_RF02>Hair_RF03_End",
                "Hair_RF05>Hair_RF06_End"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21",
                "HairB1>HairB21",
                "HairC1>HairC21",
                "HairD1>HairD21"
            ),
            SpringPresets.StiffCloth(
                "Bowknot_LB01>Bowknot_LB02_End",
                "Bowknot_RB01>Bowknot_RB02_End",
                "Hat2>Hat3",
                "Hat4>Hat5",
                "Lf_Earrings_L01>Lf_Earrings_L01_End",
                "Rt_Earrings_R01>Rt_Earrings_R01_End"
            ),
            SpringPresets.Ribbon(
                "Hat6>Hat9",
                "Hat10>Hat13"
            ),
            SpringPresets.Skirt(
                "Bowknot_LB03>Bowknot_LB06_End",
                "Bowknot_RB03>Bowknot_RB06_End"
            ),
            SpringPresets.Skirt(
                "Cape1>Cape5"
            ),
            SpringPresets.SlimGown(
                "Skirt_0_0>Skirt_11_0",
                "Skirt_0_1>Skirt_11_1",
                "Skirt_0_2>Skirt_11_2",
                "Skirt_0_3>Skirt_11_3",
                "Skirt_0_4>Skirt_11_4",
                "Skirt_0_5>Skirt_11_5",
                "Skirt_0_6>Skirt_11_6",
                "Skirt_0_7>Skirt_11_7",
                "Skirt_0_8>Skirt_11_8",
                "Skirt_0_9>Skirt_11_9",
                "Skirt_0_10>Skirt_11_10",
                "Skirt_0_11>Skirt_11_11",
                "Skirt_0_12>Skirt_11_12",
                "Skirt_0_13>Skirt_11_13",
                "Skirt_0_14>Skirt_11_14",
                "Skirt_0_15>Skirt_11_15",
                "Skirt_0_16>Skirt_11_16",
                "Skirt_0_17>Skirt_11_17",
                "Skirt_0_18>Skirt_11_18",
                "Skirt_0_19>Skirt_11_19",
                "Skirt_0_20>Skirt_11_20"
            ),
        },
        Colliders = SlimGownColliders(1.566f),
    };
}
