namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (papasha/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile PapashaDefault = new()
    {
        LodMesh = "papasha_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA7",
                "HairB1>HairB7",
                "HairE1>HairE5",
                "HairF1>HairF5",
                "HairG1>HairG4",
                "HairH1>HairH7",
                "HairI1>HairI7",
                "HairJ1>HairJ5"
            ),
            SpringPresets.LongHair(
                "HairC1>HairC9",
                "HairD1>HairD9"
            ),
            SpringPresets.StiffCloth(
                "BeltC1>BeltC5",
                "BeltD1>BeltD5",
                "TieA1>TieA5",
                "TieB1>TieB5",
                "bone0327_Lf_armor_Ctrl1_Jnt_skin>bone0327_Lf_armor_Ctrl1_Jnt_skin1"
            ),
            SpringPresets.Ribbon(
                "BeltA1>BeltA6",
                "BeltB1>BeltB5"
            ),
            SpringPresets.DrapedRibbon("Spine2",
                "bone0295_Rt_daizi_Jnt1>bone0296_Rt_daizi_Jnt21"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15"
            ),
        },
        Colliders = HumanoidColliders(1.325f),
    };
}
