namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (robella/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile RobellaDefault = new()
    {
        LodMesh = "robella_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0260_Hair_LF02>bone0261_Hair_LF03",
                "bone0279_Hair_RF02>bone0280_Hair_RF03"
            ),
            SpringPresets.LongHair(
                "PonyTailL1>PonyTailL13",
                "PonyTailR1>PonyTailR13"
            ),
            SpringPresets.Skirt(
                "Coat_0_1>Coat_7_1",
                "Coat_0_2>Coat_7_2",
                "Coat_0_3>Coat_7_3",
                "Coat_0_4>Coat_7_4",
                "Coat_0_5>Coat_7_5",
                "Coat_0_6>Coat_7_6",
                "Coat_0_7>Coat_7_7",
                "Coat_0_8>Coat_7_8",
                "Coat_0_9>Coat_7_9",
                "Coat_0_10>Coat_7_10",
                "Coat_0_11>Coat_7_11",
                "Coat_0_12>Coat_7_12",
                "Coat_0_13>Coat_7_13",
                "Coat_0_14>Coat_7_14",
                "Coat_0_15>Coat_7_15",
                "Coat_0_16>Coat_7_16",
                "Coat_0_17>Coat_7_17",
                "Coat_0_18>Coat_7_18",
                "Coat_0_19>Coat_7_19",
                "Coat_0_20>Coat_7_20"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_5_0",
                "Skirt_0_1>Skirt_5_1",
                "Skirt_0_2>Skirt_5_2",
                "Skirt_0_3>Skirt_5_3",
                "Skirt_0_4>Skirt_5_4",
                "Skirt_0_5>Skirt_5_5",
                "Skirt_0_6>Skirt_5_6",
                "Skirt_0_7>Skirt_5_7",
                "Skirt_0_8>Skirt_5_8",
                "Skirt_0_9>Skirt_5_9",
                "Skirt_0_10>Skirt_5_10",
                "Skirt_0_11>Skirt_5_11",
                "Skirt_0_12>Skirt_5_12",
                "Skirt_0_13>Skirt_5_13",
                "Skirt_0_14>Skirt_5_14",
                "Skirt_0_15>Skirt_5_15"
            ),
        },
        Colliders = HumanoidColliders(1.505f),
    };
}
