namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (robella/enforcer). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile RobellaEnforcer = new()
    {
        LodMesh = "robella_enforcer_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0260_Hair_LF02>bone0261_Hair_LF03",
                "bone0279_Hair_RF02>bone0280_Hair_RF03"
            ),
            SpringPresets.LongHair(
                "PonyTailL1>PonyTailL13",
                "PonyTailR1>PonyTailR13"
            ),
            SpringPresets.StiffCloth(
                "NeckBow_R03_1>NeckBow_R03_3"
            ),
            SpringPresets.Ribbon(
                "Sleeve_L01_2>Sleeve_L01_4",
                "Sleeve_L02_2>Sleeve_L02_4",
                "Sleeve_L03_2>Sleeve_L03_4",
                "Sleeve_L04_2>Sleeve_L04_4",
                "Sleeve_L05_2>Sleeve_L05_4",
                "Sleeve_R01_2>Sleeve_R01_4",
                "Sleeve_R02_2>Sleeve_R02_4",
                "Sleeve_R03_2>Sleeve_R03_4",
                "Sleeve_R04_2>Sleeve_R04_4",
                "Sleeve_R05_2>Sleeve_R05_4"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_4_0",
                "Skirt_0_1>Skirt_4_1",
                "Skirt_0_2>Skirt_4_2",
                "Skirt_0_3>Skirt_4_3",
                "Skirt_0_4>Skirt_4_4",
                "Skirt_0_5>Skirt_4_5",
                "Skirt_0_6>Skirt_4_6",
                "Skirt_0_7>Skirt_4_7",
                "Skirt_0_8>Skirt_4_8",
                "Skirt_0_9>Skirt_4_9",
                "Skirt_0_10>Skirt_4_10",
                "Skirt_0_11>Skirt_4_11",
                "Skirt_0_12>Skirt_4_12",
                "Skirt_0_13>Skirt_4_13",
                "Skirt_0_14>Skirt_4_14",
                "Skirt_0_15>Skirt_4_15",
                "Skirt_0_16>Skirt_4_16",
                "Skirt_0_17>Skirt_4_17"
            ),
        },
        Colliders = HumanoidColliders(1.494f),
    };
}
