namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (robella/future_navigator). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile RobellaFutureNavigator = new()
    {
        LodMesh = "robella_navigator_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0260_Hair_LF02>bone0261_Hair_LF03",
                "bone0279_Hair_RF02>bone0280_Hair_RF03"
            ),
            SpringPresets.LongHair(
                "PonyTailL1>PonyTailL13",
                "PonyTailR1>PonyTailR13"
            ),
            SpringPresets.StiffCloth(
                "bone0319_Ear_L01>bone0320_Ear_L02",
                "bone0322_Ear_R01>bone0323_Ear_R02"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_6_0",
                "Skirt_0_1>Skirt_6_1",
                "Skirt_0_2>Skirt_6_2",
                "Skirt_0_3>Skirt_6_3",
                "Skirt_0_4>Skirt_6_4",
                "Skirt_0_5>Skirt_6_5",
                "Skirt_0_6>Skirt_6_6",
                "Skirt_0_7>Skirt_6_7",
                "Skirt_0_8>Skirt_6_8",
                "Skirt_0_9>Skirt_6_9",
                "Skirt_0_10>Skirt_6_10",
                "Skirt_0_11>Skirt_6_11",
                "Skirt_0_12>Skirt_6_12",
                "Skirt_0_13>Skirt_6_13",
                "Skirt_0_14>Skirt_6_14",
                "Skirt_0_15>Skirt_6_15",
                "Skirt_0_16>Skirt_6_16",
                "Skirt_0_17>Skirt_6_17",
                "Skirt_0_18>Skirt_6_18"
            ),
        },
        Colliders = HumanoidColliders(1.494f),
    };
}
