namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (sextans/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SextansDefault = new()
    {
        LodMesh = "sextans_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB3>HairB7",
                "HairC3>HairC9",
                "HairD3>HairD7",
                "HairE3>HairE7",
                "HairF3>HairF7"
            ),
            SpringPresets.StiffCloth(
                "Cloth_L06>Cloth_L06_End",
                "Cloth_L07>Cloth_L07_End",
                "Cloth_LB04>Cloth_LB04_End",
                "Cloth_LB05>Cloth_LB05_End",
                "Cloth_R06>Cloth_R06_End",
                "Cloth_R07>Cloth_R07_End",
                "Cloth_RB04>Cloth_RB04_End",
                "Cloth_RB05>Cloth_RB05_End",
                "Collar_L02>Collar_L02End",
                "Collar_MB01>Collar_MB01_End",
                "Collar_R02>Collar_R02End",
                "Earrings_L01>Earrings_L01_End",
                "Flower_R02>Flower_R03_End",
                "Flower_R04>Flower_R04_End",
                "Flower_R05>Flower_R05_End",
                "Hat_M01>Hat_M05",
                "Lf_Hat_LB01>Lf_Hat_LB01_End",
                "Rt_Hat_RB01>Rt_Hat_RB01_End",
                "ShouderCloth_LB02>ShouderCloth_LB02End",
                "ShouderCloth_MB02>ShouderCloth_MB02End",
                "ShouderCloth_RB02>ShouderCloth_RB02End"
            ),
            SpringPresets.Ribbon(
                "SleeveA2.L>SleeveA5.L",
                "SleeveA2.R>SleeveA5.R",
                "SleeveB2.L>SleeveB4.L",
                "SleeveB2.R>SleeveB4.R",
                "SleeveC2.L>SleeveC4.L",
                "SleeveC2.R>SleeveC4.R",
                "SleeveC5.L>SleeveC6.L",
                "SleeveC5.R>SleeveC6.R",
                "SleeveD1.L>SleeveD2.L",
                "SleeveD1.R>SleeveD2.R"
            ),
            SpringPresets.DrapedRibbon("Spine2",
                "ShouderCloth_LF03>ShouderCloth_LF04_End",
                "ShouderCloth_RF03>ShouderCloth_RF04_End"
            ),
            SpringPresets.Accessory(
                "Bag_RB02_jnt_skin>Bag_RB03_jnt_skin_End"
            ),
            SpringPresets.Skirt(
                "Cloth_L01>Cloth_L03",
                "Cloth_LB02>Cloth_LB03_End",
                "Cloth_LF01>Cloth_LF03",
                "Cloth_R01>Cloth_R03",
                "Cloth_RB02>Cloth_RB03_End",
                "Cloth_RF01>Cloth_RF03"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
