namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (sextans/nocte). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SextansNocte = new()
    {
        LodMesh = "sextans_nocte_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA5",
                "HairB3>HairB7",
                "HairC3>HairC9",
                "HairD3>HairD7",
                "HairE3>HairE7",
                "HairF3>HairF7"
            ),
            SpringPresets.StiffCloth(
                "Bow_L_01>Bow_L_03",
                "Bow_R_01>Bow_R_03",
                "Cloth_L06>Cloth_L06_End",
                "Cloth_L07>Cloth_L07_End",
                "Cloth_R06>Cloth_R06_End",
                "Cloth_R07>Cloth_R07_End",
                "Earrings_L01>Earrings_L01_End",
                "Hairband_L_01>Hairband_L_02",
                "Hairband_M_01>Hairband_M_02",
                "Hairband_R_01>Hairband_R_02",
                "Zipper_01>Zipper_03"
            ),
            SpringPresets.Skirt(
                "Bow_L_04>Bow_L_07",
                "Bow_R_04>Bow_R_07"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_9_0",
                "Skirt_0_1>Skirt_9_1",
                "Skirt_0_2>Skirt_9_2",
                "Skirt_0_3>Skirt_9_3",
                "Skirt_0_4>Skirt_9_4",
                "Skirt_0_5>Skirt_9_5",
                "Skirt_0_6>Skirt_9_6",
                "Skirt_0_7>Skirt_9_7",
                "Skirt_0_8>Skirt_9_8",
                "Skirt_0_9>Skirt_9_9",
                "Skirt_0_10>Skirt_9_10",
                "Skirt_0_11>Skirt_9_11",
                "Skirt_0_12>Skirt_9_12",
                "Skirt_0_13>Skirt_9_13",
                "Skirt_0_14>Skirt_9_14",
                "Skirt_0_15>Skirt_9_15",
                "Skirt_0_16>Skirt_9_16",
                "Skirt_0_17>Skirt_9_17",
                "Skirt_0_18>Skirt_9_18",
                "Skirt_0_19>Skirt_9_19",
                "Skirt_0_20>Skirt_9_20"
            ),
        },
        Colliders = HumanoidColliders(1.566f),
    };
}
