namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (soppo/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SoppoDefault = new()
    {
        LodMesh = "soppo_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA3",
                "HairB1>HairB3",
                "HairC1>HairC4",
                "HairD1>HairD4",
                "HairG1>HairG3",
                "HairH1>HairH3",
                "HairI1>HairI2",
                "HairJ1>HairJ2",
                "HairK1>HairK2"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE11",
                "HairF1>HairF9"
            ),
            SpringPresets.StiffCloth(
                "Cloth6_R>Cloth8_R",
                "Cloth17_M>Cloth18_M",
                "Cloth23_L>Cloth24_L",
                "Cloth23_R>Cloth24_R",
                "Cloth55_L>Cloth56_L",
                "Cloth55_R>Cloth56_R",
                "Cloth57_L>Cloth58_L",
                "Cloth57_R>Cloth58_R"
            ),
            SpringPresets.Ribbon(
                "GasTankA>GasTankB"
            ),
            SpringPresets.Skirt(
                "JacketGlove2>JacketGlove5",
                "Jacket_0_2>Jacket_6_2",
                "Jacket_0_3>Jacket_6_3",
                "Jacket_0_4>Jacket_6_4",
                "Jacket_0_5>Jacket_6_5",
                "Jacket_0_6>Jacket_6_6",
                "Jacket_0_7>Jacket_6_7",
                "Jacket_0_8>Jacket_6_8",
                "Jacket_0_9>Jacket_6_9",
                "Jacket_0_10>Jacket_6_10",
                "Jacket_0_11>Jacket_6_11",
                "Jacket_0_12>Jacket_6_12",
                "Jacket_0_13>Jacket_6_13",
                "Jacket_0_14>Jacket_6_14",
                "Jacket_0_15>Jacket_6_15",
                "Jacket_0_16>Jacket_6_16",
                "Jacket_0_17>Jacket_6_17",
                "Jacket_0_18>Jacket_6_18",
                "Jacket_0_19>Jacket_6_19"
            ),
        },
        Colliders = HumanoidColliders(1.460f),
    };
}
