namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (soppo/redline). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SoppoRedline = new()
    {
        LodMesh = "soppo_redline_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA3",
                "HairB1>HairB3",
                "HairC1>HairC4",
                "HairD1>HairD4",
                "HairG1>HairG3",
                "HairH1>HairH3",
                "HairI1>HairI2",
                "HairJ1>HairJ2",
                "HairK1>HairK2"
            ),
            SpringPresets.LongHair(
                "HairE1>HairE11",
                "HairF1>HairF9"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_5_0",
                "Skirt_0_1>Skirt_5_1",
                "Skirt_0_2>Skirt_5_2",
                "Skirt_0_3>Skirt_5_3",
                "Skirt_0_4>Skirt_5_4",
                "Skirt_0_5>Skirt_5_5",
                "Skirt_0_6>Skirt_5_6",
                "Skirt_0_7>Skirt_5_7",
                "Skirt_0_8>Skirt_5_8",
                "Skirt_0_9>Skirt_5_9",
                "Skirt_0_10>Skirt_5_10",
                "Skirt_0_11>Skirt_5_11",
                "Skirt_0_12>Skirt_5_12",
                "Skirt_0_13>Skirt_5_13",
                "Skirt_0_14>Skirt_5_14",
                "Skirt_0_15>Skirt_5_15",
                "Skirt_0_16>Skirt_5_16",
                "Skirt_0_17>Skirt_5_17",
                "Skirt_0_18>Skirt_5_18",
                "Skirt_0_19>Skirt_5_19",
                "Skirt_0_20>Skirt_5_20"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
