namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (springfield/fragrance). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SpringfieldFragrance = new()
    {
        LodMesh = "springfield_fragrance_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairE2>HairE4",
                "HairF2>HairF4",
                "HairG2>HairG4",
                "HairH2>HairH4",
                "HairI2>HairI4",
                "HairJ2>HairJ4",
                "HairK1>HairK3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21",
                "HairB1>HairB21"
            ),
            SpringPresets.StiffCloth(
                "Bowtie_L01>Bowtie_L04",
                "Bowtie_R01>Bowtie_R04"
            ),
            SpringPresets.Ribbon(
                "Bow_L01>Bow_L03",
                "Bow_R01>Bow_R03"
            ),
            SpringPresets.Skirt(
                "Apron_0_0>Apron_7_0",
                "Apron_0_1>Apron_7_1",
                "Apron_0_2>Apron_7_2",
                "Apron_0_3>Apron_7_3",
                "Apron_0_4>Apron_7_4",
                "Apron_0_14>Apron_7_14",
                "Apron_0_15>Apron_7_15",
                "Apron_0_16>Apron_7_16",
                "Apron_0_17>Apron_7_17"
            ),
        },
        Colliders = HumanoidColliders(1.556f),
    };
}
