namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (springfield/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SpringfieldDefault = new()
    {
        LodMesh = "springfield_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairC1>HairC3",
                "HairD1>HairD3",
                "HairE2>HairE4",
                "HairF2>HairF4",
                "HairG2>HairG4",
                "HairH2>HairH4",
                "HairI2>HairI4",
                "HairJ2>HairJ4",
                "HairK1>HairK3",
                "bone0212_HairBandA_LB01>bone0213_HairBandA_LB03",
                "bone0215_HairBandB_LB01>bone0216_HairBandB_LB03",
                "bone0218_HairBandC_LB01>bone0218_HairBandC_LB02",
                "bone0220_HairBandD_LB01>bone0220_HairBandD_LB02",
                "bone0246_HairBandA_RB01>bone0247_HairBandA_RB03",
                "bone0249_HairBandB_RB01>bone0250_HairBandB_RB03",
                "bone0252_HairBandC_RB01>bone0252_HairBandC_RB02",
                "bone0254_HairBandD_RB01>bone0254_HairBandD_RB02"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA21",
                "HairB1>HairB21"
            ),
            SpringPresets.StiffCloth(
                "bone0287_Bowtie_L01>bone0288_Bowtie_L02",
                "bone0290_Bowtie_R01>bone0291_Bowtie_R02"
            ),
            SpringPresets.Ribbon(
                "bone0204_Sword01>bone0205_Sword02",
                "bone0336_Armor_L01>bone0337_Armor_L02",
                "bone0339_Armor_R01>bone0341_Armor_R03"
            ),
            SpringPresets.Gown(
                "Skirt_0_2>Skirt_9_2",
                "Skirt_0_3>Skirt_9_3",
                "Skirt_0_4>Skirt_9_4",
                "Skirt_0_5>Skirt_9_5",
                "Skirt_0_6>Skirt_9_6",
                "Skirt_0_7>Skirt_9_7",
                "Skirt_0_8>Skirt_9_8",
                "Skirt_0_9>Skirt_9_9",
                "Skirt_0_10>Skirt_9_10",
                "Skirt_0_11>Skirt_9_11",
                "Skirt_0_12>Skirt_9_12",
                "Skirt_0_13>Skirt_9_13",
                "Skirt_0_14>Skirt_9_14",
                "Skirt_0_15>Skirt_9_15",
                "Skirt_0_16>Skirt_9_16",
                "Skirt_0_17>Skirt_9_17",
                "Skirt_0_18>Skirt_9_18",
                "Skirt_0_19>Skirt_9_19"
            ),
        },
        Colliders = HumanoidColliders(1.561f),
    };
}
