namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (springfield/swimsuit). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile SpringfieldSwimsuit = new()
    {
        LodMesh = "springfield_swimsuit_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairD1>HairD3",
                "HairE1>HairE3",
                "HairF1>HairF3",
                "HairG1>HairG2",
                "HairH1>HairH3"
            ),
            SpringPresets.LongHair(
                "HairA1>HairA17",
                "HairB1>HairB17",
                "HairC4>HairC23"
            ),
            SpringPresets.StiffCloth(
                "Cloth_LF01>Cloth_LF02_End",
                "Cloth_RF01>Cloth_RF02_End",
                "Hat_L01>Hat_L06_End",
                "Hat_L02>Hat_L02_End",
                "Hat_L03>Hat_L03_End",
                "Hat_L09>Hat_L09_End",
                "Hat_MB01>Hat_MB02_End",
                "Hat_MF01>Hat_MF02_End",
                "Hat_R01>Hat_R02_End"
            ),
            SpringPresets.Ribbon(
                "Glasses01>Glasses02"
            ),
            SpringPresets.SlimGown(
                "Skirt_0_0>Skirt_11_0",
                "Skirt_0_1>Skirt_11_1",
                "Skirt_0_2>Skirt_11_2",
                "Skirt_0_3>Skirt_11_3",
                "Skirt_0_4>Skirt_11_4",
                "Skirt_0_5>Skirt_11_5",
                "Skirt_0_6>Skirt_11_6",
                "Skirt_0_7>Skirt_11_7",
                "Skirt_0_8>Skirt_11_8",
                "Skirt_0_9>Skirt_11_9",
                "Skirt_0_10>Skirt_11_10",
                "Skirt_0_11>Skirt_11_11",
                "Skirt_0_12>Skirt_11_12",
                "Skirt_0_13>Skirt_11_13",
                "Skirt_0_14>Skirt_11_14",
                "Skirt_0_15>Skirt_11_15",
                "Skirt_0_16>Skirt_11_16",
                "Skirt_0_17>Skirt_11_17",
                "Skirt_0_18>Skirt_11_18",
                "Skirt_0_19>Skirt_11_19",
                "Skirt_0_20>Skirt_11_20"
            ),
        },
        Colliders = SlimGownColliders(1.556f),
    };
}
