namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (vector/vivi). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile VectorVivi = new()
    {
        LodMesh = "vector_vivi_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairE1>HairE4",
                "HairF1>HairF2",
                "HairG1>HairG2",
                "HairH1>HairH3"
            ),
            SpringPresets.Ribbon(
                "bone0389_Tie_M>bone0391_Tie_M3"
            ),
            SpringPresets.Skirt(
                "Jacket_0_2>Jacket_7_2",
                "Jacket_0_3>Jacket_7_3",
                "Jacket_0_4>Jacket_7_4",
                "Jacket_0_5>Jacket_7_5",
                "Jacket_0_6>Jacket_7_6",
                "Jacket_0_7>Jacket_7_7",
                "Jacket_0_8>Jacket_7_8",
                "Jacket_0_9>Jacket_7_9",
                "Jacket_0_10>Jacket_7_10",
                "Jacket_0_11>Jacket_7_11",
                "Jacket_0_12>Jacket_7_12",
                "Jacket_0_13>Jacket_7_13",
                "Jacket_0_14>Jacket_7_14"
            ),
            SpringPresets.Skirt(
                "Skirt_0_0>Skirt_5_0",
                "Skirt_0_1>Skirt_5_1",
                "Skirt_0_2>Skirt_5_2",
                "Skirt_0_3>Skirt_5_3",
                "Skirt_0_4>Skirt_5_4",
                "Skirt_0_5>Skirt_5_5",
                "Skirt_0_6>Skirt_5_6",
                "Skirt_0_7>Skirt_5_7",
                "Skirt_0_8>Skirt_5_8",
                "Skirt_0_9>Skirt_5_9",
                "Skirt_0_10>Skirt_5_10",
                "Skirt_0_11>Skirt_5_11",
                "Skirt_0_12>Skirt_5_12",
                "Skirt_0_13>Skirt_5_13",
                "Skirt_0_14>Skirt_5_14",
                "Skirt_0_15>Skirt_5_15",
                "Skirt_0_16>Skirt_5_16",
                "Skirt_0_17>Skirt_5_17"
            ),
        },
        Colliders = HumanoidColliders(1.480f),
    };
}
