namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (vector/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile VectorDefault = new()
    {
        LodMesh = "vector_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairC1>HairC2",
                "HairD1>HairD2",
                "HairE1>HairE5",
                "HairF1>HairF3",
                "HairG1>HairG2",
                "HairH1>HairH3"
            ),
            SpringPresets.StiffCloth(
                "bone0284_cord_R>bone0284_cord_R1",
                "bone0329_cord_L>bone0329_cord_L1",
                "bone0382_c_Lf_line_Jnt4>bone0382_c_Lf_line_Jnt41",
                "bone0384_c_Rt_line_Jnt4>bone0384_c_Rt_line_Jnt41"
            ),
            SpringPresets.DrapedRibbon("Spine2",
                "bone0281_c_Rt_line_Jnt1>bone0282_c_Rt_line_Jnt21",
                "bone0326_c_Lf_line_Jnt1>bone0327_c_Lf_line_Jnt21"
            ),
            SpringPresets.Skirt(
                "Jacket_0_2>Jacket_7_2",
                "Jacket_0_3>Jacket_7_3",
                "Jacket_0_4>Jacket_7_4",
                "Jacket_0_5>Jacket_7_5",
                "Jacket_0_6>Jacket_7_6",
                "Jacket_0_7>Jacket_7_7",
                "Jacket_0_8>Jacket_7_8",
                "Jacket_0_9>Jacket_7_9",
                "Jacket_0_10>Jacket_7_10",
                "Jacket_0_11>Jacket_7_11",
                "Jacket_0_12>Jacket_7_12",
                "Jacket_0_13>Jacket_7_13",
                "Jacket_0_14>Jacket_7_14"
            ),
        },
        Colliders = HumanoidColliders(1.412f),
    };
}
