namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (voymastina/default). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile VoymastinaDefault = new()
    {
        LodMesh = "voymastina_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "HairA1>HairA3",
                "HairB2>HairB4",
                "HairC2>HairC4"
            ),
            SpringPresets.LongHair(
                "HairD2>HairD21",
                "HairE1>HairE20",
                "HairF1>HairF20",
                "HairG1>HairG21",
                "HairH1>HairH21"
            ),
        },
        Colliders = HumanoidColliders(1.799f),
    };
}
