namespace WOMENACE.Code;

internal static partial class SpringBodyProfiles
{
    // Generated by scripts/pmx_to_menace.py from the PMX's physics bodies
    // (voymastina/erwin). Tune it in place: the converter never rewrites it.
    internal static readonly SpringBodyProfile VoymastinaErwin = new()
    {
        LodMesh = "voymastina_erwin_LOD0",
        Chains = new[]
        {
            SpringPresets.ShortHair(
                "bone0343_Hair_L01>bone0345_Hair_L03A",
                "bone0346_Hair_R01>bone0348_Hair_R03A"
            ),
            SpringPresets.LongHair(
                "PonyTail1>PonyTail19"
            ),
            SpringPresets.StiffCloth(
                "bone0341_Bangs_MF01>bone0342_Bangs_MF02A"
            ),
            SpringPresets.Skirt(
                "Coat_0_0>Coat_5_0",
                "Coat_0_1>Coat_5_1",
                "Coat_0_2>Coat_5_2",
                "Coat_0_3>Coat_5_3",
                "Coat_0_4>Coat_5_4",
                "Coat_0_5>Coat_5_5",
                "Coat_0_6>Coat_5_6",
                "Coat_0_7>Coat_5_7",
                "Coat_0_8>Coat_5_8",
                "Coat_0_9>Coat_5_9",
                "Coat_0_10>Coat_5_10",
                "Coat_0_11>Coat_5_11",
                "Coat_0_12>Coat_5_12",
                "Coat_0_13>Coat_5_13",
                "Coat_0_14>Coat_5_14",
                "Coat_0_15>Coat_5_15"
            ),
        },
        Colliders = HumanoidColliders(1.799f),
    };
}
